### ISSUE TITLE
Quick Fix: Description says SmashStreamHelper instead of TournamentStreamHelper

### ISSUE THREAD

**Issue by Tasabu** [joaorb64/StreamHelperAssets#280]
![image](https://user-images.githubusercontent.com/116982612/223513310-58765bb7-d5fb-4f8f-bdd0-817144fda11f.png)

**Comment by Wolfy76700** [comment]
Wait where? I can't find it

**Comment by Tasabu** [comment]
> Wait where? I can't find it

If you go to Shino's github and look at either his overview or his repositories, and you find the StreamHelperAssets repository, the quick description before you actually go into the repository is where my screenshot comes from

**Comment by Wolfy76700** [comment]
Fixed
