### ISSUE TITLE
Can't save thumbnails

### ISSUE THREAD

**Issue by PaulowebTV** [joaorb64/StreamHelperAssets#353]
I keep getting this error.

![noname](https://github.com/joaorb64/StreamHelperAssets/assets/111398997/be598bc9-2687-4367-b3f0-8de47cb52c4e)

**Comment by Wolfy76700** [comment]
Hi, did you make sure to extract the software in a folder where you have user access? (e.g. the Desktop or Documents folder, not the Program Files folder)

If so, please send us the `log.txt` and `log_error.txt` files present in the `assets` folder, also which version of the software are you using?

**Comment by Wolfy76700** [comment]
I can confirm, your install seems to be in a folder you do not have any access to, can you please try to re-extract the software from scratch in a folder ou do have access to please?

**Comment by PaulowebTV** [comment]
Yes, I can do that. I'm gonna install it on Desktop and test if it works.

Em ter., 22 de ago. de 2023 11:32, Mathias Wolfbrok <
***@***.***> escreveu:

**Comment by PaulowebTV** [comment]
I did what you recommended and my thumbs are being saved now. Thanks.
