### ISSUE TITLE
SSBU Hollow Bastion stage missing

### ISSUE THREAD

**Issue by Smoolak** [joaorb64/StreamHelperAssets#42]
Hi,

On October 18 a new stage for Super Smash Bros. Ultimate was released. Its Hollow Bastion, you guys can find it here: https://www.ssbwiki.com/Hollow_Bastion

**Comment by joaorb64** [comment]
I was waiting for SmashGG to add support to it for me to get its ID. I guess I forgot to add it! Will try to add it today, thanks for opening the issue!

**Comment by joaorb64** [comment]
Fixed in https://github.com/joaorb64/StreamHelperAssets/commit/606e761b8daf5fe8b8603bc82c0779e43af448f0. Soon the auto sequence will complete and you'll see updates for "base_files" and "stage_icon".
Thanks for pointing that out!
